---
version: "2.1"
services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop:latest
    container_name: snapdrop
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/snapdrop:/config
    ports:
      - 82:80
      - 8443:443
    restart: unless-stopped
