version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
     environment:
      - APACHE_PORT=11000 
      - APACHE_IP_BINDING=127.0.0.1
      - TALK_PORT=3478
      - NEXTCLOUD_DATADIR=/mnt/data/nxtcld
      - SKIP_DOMAIN_VALIDATION=true
