version: '3.1' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: wordpress-proxy
    networks:
      - wordpress_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: wordpress-letsencrypt
    depends_on:
      - proxy
    networks:
      - wordpress_network
    volumes:
      - ./proxy/certs:/etc/nginx/certs:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  db:
    image: yobasystems/alpine-mariadb:latest
    container_name: wordpress-mysql
    networks:
      - wordpress_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_DATABASE: wordpressdb
      - MYSQL_USER: exampleuser
      - MYSQL_PASSWORD: examplepass
      - MYSQL_RANDOM_ROOT_PASSWORD: 'examplepass'
    restart: unless-stopped
  
  app:
    image: wordpress:latest
    container_name: wordpress-app
    networks:
      - wordpress_network
    depends_on:
      - letsencrypt
      - proxy
      - db
    volumes:
      - wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST: exampledomain
      - LETSENCRYPT_HOST: exampledomain
      - LETSENCRYPT_EMAIL: examplemail
      - WORDPRESS_DB_HOST: db
      - WORDPRESS_DB_USER: exampleuser
      - WORDPRESS_DB_PASSWORD: examplepass
      - WORDPRESS_DB_NAME: wordpressdb
    restart: unless-stopped

volumes:
  wordpress:
  db:

networks:
  wordpress_network:
